### ISSUE TITLE
fulltextsearch

### ISSUE THREAD

**Issue by cederigo** [ese-unibe-ch/ese2010-team5#17]
space between words is either and or or
update:

simple search (not and or or)
filter search result based on tags

on every page: search box 
results:
- separate page showing found usernames and questions(title,content)
- max 10 results

**Comment by rodriges17** [comment]
gonna change this to also include the titles of the questions, the authors and as well the tags.

**Comment by cederigo** [comment]
title is done already.

**Comment by cederigo** [comment]
done in fae44b70710d026ee17963f80694b11bc012542e
